plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = '0.0.1'
group = 'com.mbx'
base { archivesName = 'DynamicKeycards' }

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

neoForge {
    version = '21.1.233'
    runs {
        client { client() }
        server { server() }
    }
    mods {
        dynamickeycards { sourceSet(sourceSets.main) }
    }
}

jar {
    // <ModName>-<modversion>-<gameversion>.jar
    archiveVersion = "${project.version}-1.21.1"
    manifest {
        attributes 'Implementation-Version': project.version
    }
}
